Add `rds_read_replica_v3` resource
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1037
Opened 2021-04-29 11:57 UTC by outcatcher

## Summary of the Pull Request
Implement `opentelekomcloud_rds_read_replica_v3`

Update SDK

Resolve #1004 

## PR Checklist

* [x] Refers to: #1004 
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

Resource:
```
=== RUN   TestAccRdsReadReplicaV3Basic
--- PASS: TestAccRdsReadReplicaV3Basic (1273.94s)
PASS

Process finished with the exit code 0

```

Import:
```
In progress
```

2021-04-29 16:18 UTC, anton-sidelnikov requested changes

2021-04-29 16:18 UTC, anton-sidelnikov commented on opentelekomcloud/services/rds/resource_opentelekomcloud_rds_read_replica_v3.go
> +		return fmt.Errorf("eror deleting read replica instance: %w", err)
error

2021-04-29 16:49 UTC, anton-sidelnikov submitted a review, later dismissed

2021-04-29 19:11 UTC, lego963 requested changes
Doc is empty

2021-05-18 10:07 UTC, lego963 approved these changes

2021-05-18 10:48 UTC, merged