[CCE] Update addon templates
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1172
Opened 2021-06-28 13:56 UTC by lego963

## Summary of the Pull Request
Update addon templates for both k8s versions
Remove redundant addon, which cannot be installed for `1.17`/`1.19`
Fixes; #1154

## PR Checklist

* [x] Refers to: #1154
* [x] Documentation updated.

2021-06-28 14:21 UTC, outcatcher approved these changes, later dismissed

2021-06-28 14:26 UTC, anton-sidelnikov approved these changes, later dismissed

2021-06-29 09:13 UTC, outcatcher requested changes
Please add a changelog entry

2021-06-29 10:32 UTC, anton-sidelnikov approved these changes

2021-06-29 11:47 UTC, outcatcher approved these changes

2021-06-29 12:52 UTC, merged