[KMS] Add missing field `expiration_time`
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1284
Opened 2021-08-12 15:01 UTC by lego963

## Summary of the Pull Request
Fix issue with missing field `expiration_time`

## PR Checklist

* [x] Refers to: #1283
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [x] Schema updated.
* [ ] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccKmsKeyV1DataSource_basic
--- PASS: TestAccKmsKeyV1DataSource_basic (77.63s)
PASS

Process finished with the exit code 0
```

2021-08-12 15:10 UTC, outcatcher requested changes

2021-08-12 15:10 UTC, outcatcher commented on opentelekomcloud/services/kms/data_source_opentelekomcloud_kms_key_v1.go
> +					WaitingForEnableState, EnabledState, DisabledState, PendingDeletionState, WaitingImportState,
Maybe better to keep them in a column?

2021-08-12 15:10 UTC, outcatcher commented on releasenotes/notes/d-kms-fix-9c118e8b71548a5e.yaml
> +    **[KMS]** Add missing field ``expiration_time`` in ``data_source/opentelekomcloud_kms_key_v1`` (#1284 `https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1284`_)
Please add other changes done to the RN, including change of `ForceNew` fields

2021-08-12 15:20 UTC, outcatcher approved these changes

2021-08-12 15:30 UTC, anton-sidelnikov submitted a review, later dismissed

2021-08-12 15:30 UTC, outcatcher submitted a review, later dismissed

2021-08-12 16:56 UTC, anton-sidelnikov submitted a review, later dismissed

2021-08-13 09:20 UTC, outcatcher approved these changes

2021-08-13 09:31 UTC, merged