[LB] Implement `resource/opentelekomcloud_lb_loadbalancer_v3`
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1501
Opened 2021-11-01 09:25 UTC by lego963

## Summary of the Pull Request
Implement `resource/opentelekomcloud_lb_loadbalancer_v3`
Refers to: #1486

## PR Checklist

* [x] Refers to: #1486
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [x] Schema updated.
* [ ] Release notes added.

## Acceptance Steps Performed

```
TBD
```

2021-11-01 13:25 UTC, outcatcher requested changes

2021-11-01 13:25 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/common.go
> +type ContextKey string
There is already `common.ClientCtxKey` type

2021-11-01 13:25 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/common.go
> +}
Please use methods from `common` package

2021-11-01 13:25 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +	}
This wait is not actually needed

2021-11-01 13:25 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +	}
Same as previous wait

2021-11-01 13:25 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +				Set:      schema.HashString,
`Set` argument is not required here, it's set by default

2021-11-01 13:25 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +				Set:      schema.HashString,
`Set` argument can be skipped

2021-11-01 13:25 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +		},
Timeouts are not required here. There are no actual waits.

2021-11-01 13:25 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +			diag.FromErr(err)
Missing `return`

2021-11-01 15:10 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +	}
You can avoid this read storing public IP values in the resource data

2021-11-01 16:22 UTC, outcatcher requested changes

2021-11-01 16:22 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +						},
**Optional:** Those fields can be just `id` and `address`, as the parent field is named `public_ip`

2021-11-01 16:22 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +		}
You should set other fields from the schema, e.g:
```
		publicIpInfo[i] = map[string]interface{}{
			"public_ip_id":      v.PublicIpID,
			"public_ip_address": v.PublicIpAddress,
			"bandwidth_name": d.Get("public_ip.0.bandwidth_name").(string)
			...
		}
```

or init it with a value from the schema:
```
info := d.Get("public_ip.0").(map[string]interface{})
info["public_ip_id"] = v.publicIpID
...
publicIpInfo[i] = info
```

(or replace `0` with `i` if you want to support a list of public IPs

2021-11-01 16:22 UTC, outcatcher commented on opentelekomcloud/services/elb/v3/resource_opentelekomcloud_lb_loadbalancer_v3.go
> +		nwV1Client, err := config.NetworkingV2Client(config.GetRegion(d))
it's `nwV2Client` now :)

2021-11-02 08:01 UTC, outcatcher approved these changes, later dismissed

2021-11-02 08:16 UTC, anton-sidelnikov requested changes

2021-11-02 08:16 UTC, anton-sidelnikov commented on docs/resources/lb_loadbalancer_v3.md
> +* `name` - (Optional) Human-readable name for the LoadBalancer.
can be inhuman?)

2021-11-02 08:24 UTC, outcatcher approved these changes

2021-11-02 08:27 UTC, anton-sidelnikov approved these changes

2021-11-02 08:51 UTC, merged