rds instances datasource
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1739
Opened 2022-05-19 12:42 UTC by vladimirvshivkov

## Summary of the Pull Request

## PR Checklist

* [ ] Refers to: #1736
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.
* [ ] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccSomethingV0_basic
--- PASS: TestAccSomethingV0_basic (101.71s)
=== RUN   TestAccSomethingV0_timeout
--- PASS: TestAccSomethingV0_timeout (128.67s)
PASS

Process finished with exit code 0
```

2022-05-24 10:50 UTC, lego963 requested changes

2022-05-24 10:50 UTC, lego963 commented on opentelekomcloud/services/rds/data_source_opentelekomcloud_rds_instances_v3.go
> +			},
this is unsupported in the OTC

2022-05-24 10:50 UTC, lego963 commented on go.mod
> +	github.com/aws/aws-sdk-go v1.37.0
do we need it?

2022-05-24 10:50 UTC, lego963 commented on opentelekomcloud/acceptance/rds/data_source_opentelekomcloud_rds_instances_v3_test.go
> +}
We don't need to create network infra, can you use predefined infra like in `rds_instance_v3` test?

- `common.DataSourceSecGroupDefault`
- `common.DataSourceSubnet`

2022-05-24 10:50 UTC, lego963 commented on opentelekomcloud/services/rds/data_source_opentelekomcloud_rds_instances_v3.go
> +package rds
opentelekomcloud/services/rds/data_source_opentelekomcloud_rds_instances_v3.go
should be
opentelekomcloud/services/rds/data_source_opentelekomcloud_rds_instance_v3.go

2022-05-24 10:50 UTC, lego963 commented on opentelekomcloud/services/rds/data_source_opentelekomcloud_rds_instances_v3.go
> +						},
same

2022-05-24 10:50 UTC, lego963 commented on opentelekomcloud/services/rds/data_source_opentelekomcloud_rds_instances_v3.go
> +	listOpts := instances.ListOpts{
you missed `id` filter

2022-05-24 10:50 UTC, lego963 commented on opentelekomcloud/services/rds/data_source_opentelekomcloud_rds_instances_v3.go
> +	for _, item := range allInstances.Instances {
in `data_source/opentelekomcloud_rds_instance_v3` we should return only single instance

```
	if len(allInstances) < 1 {
		return common.DataSourceTooFewDiag
	}

	if len(allInstances) > 1 {
		return common.DataSourceTooManyDiag
	}
```

2022-05-24 11:09 UTC, vladimirvshivkov commented on go.mod
> +	github.com/aws/aws-sdk-go v1.37.0
go mod thinks we do

2022-05-26 06:43 UTC, lego963 commented on opentelekomcloud/services/rds/data_source_opentelekomcloud_rds_instance_v3.go
> +	for _, item := range allInstances.Instances {
you don't need to use `for` if you have 1 instance

2022-05-27 11:01 UTC, lego963 commented on docs/data-sources/rds_instance_v3.md
> +
add small description here please

2022-05-27 11:05 UTC, vladimirvshivkov commented on docs/data-sources/rds_instance_v3.md
> +
done

2022-05-27 11:10 UTC, lego963 approved these changes

2022-05-27 11:17 UTC, anton-sidelnikov approved these changes

2022-05-27 11:22 UTC, merged