ecs ds
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1772
Opened 2022-06-20 15:00 UTC by vladimirvshivkov

## Summary of the Pull Request

## PR Checklist

* [ ] Refers to: #xxx
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.
* [ ] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccSomethingV0_basic
--- PASS: TestAccSomethingV0_basic (101.71s)
=== RUN   TestAccSomethingV0_timeout
--- PASS: TestAccSomethingV0_timeout (128.67s)
PASS

Process finished with exit code 0
```

2022-06-27 13:11 UTC, anton-sidelnikov submitted a review, later dismissed

2022-06-27 13:27 UTC, lego963 requested changes

2022-06-27 13:27 UTC, lego963 commented on opentelekomcloud/acceptance/ecs/data_source_opentelekomcloud_compute_instance_v2_test.go
> +			common.TestAccPreCheckAdminOnly(t)
is it required?

2022-06-27 13:27 UTC, lego963 commented on docs/data-sources/ecs_instance_v1.md
> +data "opentelekomcloud_ecs_instance_v1" "instance" {
is it ecs_instance or compute_instance?

2022-06-27 13:27 UTC, lego963 commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +		return diag.Errorf("Error creating compute client: %s", err)
use errCreateV2Client

2022-06-27 13:27 UTC, lego963 commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +			},
use common.TagsSchema()

2022-06-27 13:27 UTC, lego963 commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +	}
duplicate code, you can drop it

2022-06-27 13:27 UTC, lego963 commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +		_ = d.Set("power_state", currentStatus)
do not ingnore errors

2022-06-27 13:27 UTC, lego963 commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +		_ = d.Set("tags", instanceTags)
same with errors

2022-06-27 13:27 UTC, lego963 commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +	instanceTags, err := tags.List(client, server.ID).Extract()
is it working?
and 
// List is a method of getting the tags of all service

2022-06-28 07:01 UTC, vladimirvshivkov commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +	instanceTags, err := tags.List(client, server.ID).Extract()
good question)

2022-06-28 13:26 UTC, lego963 approved these changes

2022-06-28 13:35 UTC, merged