[KMS] Add `desired_state` in schema of `kms_key_v1`
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1806
Opened 2022-07-12 13:01 UTC by anton-sidelnikov

## Summary of the Pull Request
Added ability to canceling the Scheduled Deletion of a CMK

## PR Checklist

* [x] Refers to: #1804 
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccKmsKeyV1_basic
--- PASS: TestAccKmsKeyV1_basic (83.71s)
=== RUN   TestAccKmsKey_isEnabled
--- PASS: TestAccKmsKey_isEnabled (115.14s)
=== RUN   TestAccKmsKey_rotation
--- PASS: TestAccKmsKey_rotation (50.18s)
=== RUN   TestAccKmsKey_cancelDeletion
--- PASS: TestAccKmsKey_cancelDeletion(51.07s)
PASS

Process finished with the exit code 0
```

2022-07-12 13:33 UTC, artem-lifshits submitted a review, later dismissed

2022-07-12 14:15 UTC, vladimirvshivkov commented on opentelekomcloud/acceptance/kms/resource_opentelekomcloud_kms_key_v1_test.go
> +  desired_state   = "ENABLED"
why would you decided to use this way instead of:
`enabled = true`?

2022-07-12 14:26 UTC, vladimirvshivkov commented on opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go
> +				ValidateFunc: validation.StringInSlice([]string{
also bool won't require validation

2022-07-12 14:31 UTC, vladimirvshivkov commented on opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go
> +	if d.Get("desired_state").(string) == "ENABLED" {
if is_enabled check the state of key's pending deletion and reenable if required

2022-07-12 14:33 UTC, vladimirvshivkov requested changes
desired state its kinda weird arg for terraform's declarative code

2022-07-12 15:01 UTC, anton-sidelnikov commented on opentelekomcloud/acceptance/kms/resource_opentelekomcloud_kms_key_v1_test.go
> +  desired_state   = "ENABLED"
this resource already have is_enabled parameter

2022-07-13 09:04 UTC, anton-sidelnikov commented on opentelekomcloud/services/kms/resource_opentelekomcloud_kms_key_v1.go
> +	if d.Get("desired_state").(string) == "ENABLED" {
> desired state its kinda weird arg for terraform's declarative code

Yes, desided to rename it allow_cancel_deletion and make it bool

2022-07-13 10:46 UTC, vladimirvshivkov approved these changes

2022-07-13 10:55 UTC, merged