[IAM] Add aksk gpg encryption for ``resource/opentelekomcloud_identity_credential_v3``
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1807
Opened 2022-07-13 10:41 UTC by vladimirvshivkov

## Summary of the Pull Request

## PR Checklist

* [ ] Refers to: #xxx
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.
* [ ] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccIdentityV3Credential_basic
--- PASS: TestAccIdentityV3Credential_basic (57.35s)
PASS

Process finished with exit code 0
```

2022-07-13 12:45 UTC, anton-sidelnikov requested changes

2022-07-13 12:45 UTC, anton-sidelnikov commented on opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go
> +  pgp_key = "mDMEYs6CMxYJKwYBBAHaRw8BAQdAoF5tLs+wvwvF+A5+mAfdGLrwz3bKdKsUA3iuxQcDUZe0JFZsYWRpbWlyIFZzaGl2a292IDxlbnJyb3VAZ21haWwuY29tPoiZBBMWCgBBFiEEDdv9KvPC2UDkSDiCKWyGs27oaG0FAmLOgjMCGwMFCQPCZwAFCw
How works keybase? can you add some test for example?

2022-07-13 13:47 UTC, vladimirvshivkov commented on opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go
> +  pgp_key = "mDMEYs6CMxYJKwYBBAHaRw8BAQdAoF5tLs+wvwvF+A5+mAfdGLrwz3bKdKsUA3iuxQcDUZe0JFZsYWRpbWlyIFZzaGl2a292IDxlbnJyb3VAZ21haWwuY29tPoiZBBMWCgBBFiEEDdv9KvPC2UDkSDiCKWyGs27oaG0FAmLOgjMCGwMFCQPCZwAFCw
this is hardly automately testable, I will attach terraform hcl that I used to test:
```
resource opentelekomcloud_identity_credential_v3 aksk {
  description = "This is one and unique test AK/SK"
  pgp_key = "keybase:enrrou"
}

output "encrypted_secret" {
  value = "${opentelekomcloud_identity_credential_v3.aksk.secret}"  
}
``` 

gives next output:
```
terraform apply
╷
│ Warning: Provider development overrides are in effect
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # opentelekomcloud_identity_credential_v3.aksk will be created
  + resource "opentelekomcloud_identity_credential_v3" "aksk" {
      + access          = (sensitive value)
      + create_time     = (known after apply)
      + description     = "This is one and unique test AK/SK"
      + id              = (known after apply)
      + key_fingerprint = (known after apply)
      + last_use_time   = (known after apply)
      + pgp_key         = "keybase:enrrou"
      + secret          = (known after apply)
      + status          = (known after apply)
      + user_id         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + encrypted_secret = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opentelekomcloud_identity_credential_v3.aksk: Creating...
opentelekomcloud_identity_credential_v3.aksk: Creation complete after 2s [id=JKOXFCBLZ9DGYUEFH37M]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

encrypted_secret = "wcFMA+B3lb4MZcBWARAAXSeaKG+JSHCOkyCrh6e0T5eRtbq4waB5waCaa81VXbgdr3+b+uaVr1ssNZ5VfJCtdM24CC1zpbEmVla7Zsjjk4ikxO3d0Y13MtKYEJ36hq4sABERnn1W3RLIAwH1e15DpVY7qMp1/Mu04MGoKnysNfGg4aCPhUycOHuxdIY0snmPVhKXn9wdqh9ERQCVrouu4ZszCah7A+yniB1/lOdtgwdjoaqhsqd50snPRVq6Ri1qIn487LdYCxtyjoOVHu9N8XALtZljHOnBrmXnAveyhiLHRlhcHmV93fm6Vf6m6bIFVVrIVAhT6JWaIGTduvru2Fh4Hy11CYyG+LlcK1lcIYbsND2jKEDbhXg/VamphYWk8r0MfxAQH30DvMQQIUCQExTCcX5rGJBWKit5pJomQQREcsaLCE9yEpNnKIvQq0eHKCgjrRisc8riZeWBDEUgU8MrErMii5pBfX8uWzhYtjbuQrhX/vzkS9K391dc7G1nENlETg4DhVtCGDHqkbDaD+S/LPSKg0Y0ivJQPUrCQ3z4blAbyny/Fw+8ystIalfYIw/h4+ODaOK18mv7CW+G5cKihOdnxPw6l9XQV0F2DyVSfx3aqSH4AdGTiC+JiuVeV/lftoxEpH7GfZ2EhdwKuR0x29DuliVCnSkovMhHyX/8qsoCM47ZZfTF7wO1GEfS4AHksba4LYMpDkezperFudjsxuHM6OB84KfhrTDgkOK42qIZ4IXlKttXjMXyd/+DiSzOn6gGYpV/jucqvyQiIML3qGARAbngP+M0AolmXFWsTeDN5FHKS9r0KqcDNpPy407WiQHiOXr4i+E8EQA="
```

2022-07-13 13:54 UTC, anton-sidelnikov approved these changes, later dismissed

2022-07-13 13:58 UTC, vladimirvshivkov commented on opentelekomcloud/acceptance/iam/resource_opentelekomcloud_identity_credential_v3_test.go
> +  pgp_key = "mDMEYs6CMxYJKwYBBAHaRw8BAQdAoF5tLs+wvwvF+A5+mAfdGLrwz3bKdKsUA3iuxQcDUZe0JFZsYWRpbWlyIFZzaGl2a292IDxlbnJyb3VAZ21haWwuY29tPoiZBBMWCgBBFiEEDdv9KvPC2UDkSDiCKWyGs27oaG0FAmLOgjMCGwMFCQPCZwAFCw
added test just for you)

2022-07-14 07:54 UTC, anton-sidelnikov approved these changes

2022-07-14 08:03 UTC, merged