get ecs pass
opentelekomcloud/terraform-provider-opentelekomcloud pull request #1947
Opened 2022-09-27 08:24 UTC by vladimirvshivkov

## Summary of the Pull Request

## PR Checklist

* [ ] Refers to: #
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.
* [ ] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccSomethingV0_basic
--- PASS: TestAccSomethingV0_basic (101.71s)
=== RUN   TestAccSomethingV0_timeout
--- PASS: TestAccSomethingV0_timeout (128.67s)
PASS

Process finished with exit code 0
```

2022-10-04 18:05 UTC, anton-sidelnikov requested changes

2022-10-04 18:05 UTC, anton-sidelnikov commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +				// Sensitive: true,
Why commented?

2022-10-04 18:47 UTC, vladimirvshivkov commented on opentelekomcloud/services/ecs/data_source_opentelekomcloud_compute_instance_v2.go
> +				// Sensitive: true,
fixed, thanks

2022-10-05 09:06 UTC, anton-sidelnikov approved these changes

2022-10-05 09:25 UTC, artem-lifshits approved these changes

2022-10-05 09:35 UTC, merged