[CES]: `opentelekomcloud_ces_alarmrule` alarm types & frequency features
opentelekomcloud/terraform-provider-opentelekomcloud pull request #2189
Opened 2023-06-07 16:50 UTC by artem-lifshits

## Summary of the Pull Request
Introcude `alarm_type` and `alarm_frequency` arguments for `resource/opentelekomcloud_ces_alarmrule`.

## PR Checklist

* [x] Refers to: #1896, #1230
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccSomethingV0_basic
--- PASS: TestAccSomethingV0_basic (101.71s)
=== RUN   TestAccSomethingV0_timeout
--- PASS: TestAccSomethingV0_timeout (128.67s)
PASS

Process finished with exit code 0
```

2023-06-07 17:21 UTC, anton-sidelnikov requested changes

2023-06-07 17:21 UTC, anton-sidelnikov commented on opentelekomcloud/acceptance/ces/resource_opentelekomcloud_ces_alarmrule_test.go
> +					testCESAlarmRuleExists(resourceAlarmRuleName, &ar),
add more checks please alarm_type, namespace, metric_name, alarm_frequency

2023-06-07 17:21 UTC, anton-sidelnikov requested changes

2023-06-07 17:21 UTC, anton-sidelnikov commented on releasenotes/notes/ces_alarm_types-0e1d3534be3db654.yaml
> +    **[CES]** Introduce `alarm_type` and `alarm_frequency` arguments for ``resource/opentelekomcloud_ces_alarmrule`` (`# <https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/
add number of pr

2023-06-09 09:08 UTC, anton-sidelnikov approved these changes

2023-06-09 09:10 UTC, vladimirvshivkov approved these changes

2023-06-09 09:28 UTC, merged