IAM: Provider resource overhaul
opentelekomcloud/terraform-provider-opentelekomcloud pull request #2232
Opened 2023-07-19 15:37 UTC by artem-lifshits

## Summary of the Pull Request
Implement new resource ``opentelekomcloud_identity_provider`` to manage identity providers with SAML/OIDC support

## PR Checklist

* [x] Refers to: #2177
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccIdentityProviderBasic
--- PASS: TestAccIdentityProviderBasic (50.26s)
=== RUN   TestAccIdentityProviderOIDC
--- PASS: TestAccIdentityProviderOIDC (51.19s)
=== RUN   TestAccIdentityOIDCProvider_import
--- PASS: TestAccIdentityOIDCProvider_import (33.64s)
=== RUN   TestAccIdentitySamlProvider_import
--- PASS: TestAccIdentitySamlProvider_import (35.68s)
PASS

Process finished with the exit code 0

```

2023-07-19 16:10 UTC, vladimirvshivkov submitted a review, later dismissed
looks fine

2023-07-19 16:12 UTC, Polina-Gubina submitted a review, later dismissed

2023-07-19 16:13 UTC, vladimirvshivkov approved these changes, later dismissed

2023-07-19 16:24 UTC, Polina-Gubina approved these changes, later dismissed

2023-07-19 16:45 UTC, vladimirvshivkov submitted a review, later dismissed

2023-07-19 17:17 UTC, anton-sidelnikov requested changes

2023-07-19 17:17 UTC, anton-sidelnikov commented on opentelekomcloud/services/iam/resource_opentelekomcloud_identity_provider.go
> +			"access_config": {
conflict with metadata

2023-07-19 17:17 UTC, anton-sidelnikov commented on opentelekomcloud/services/iam/resource_opentelekomcloud_identity_provider.go
> +	localRules := []mappings.LocalRuleOpts{
try to make rules editable

2023-07-19 18:44 UTC, artem-lifshits commented on opentelekomcloud/services/iam/resource_opentelekomcloud_identity_provider.go
> +			"access_config": {
done

2023-07-19 18:44 UTC, artem-lifshits commented on opentelekomcloud/services/iam/resource_opentelekomcloud_identity_provider.go
> +	localRules := []mappings.LocalRuleOpts{
done

2023-07-19 22:10 UTC, Aloento approved these changes

2023-07-20 08:45 UTC, anton-sidelnikov approved these changes

2023-07-20 08:55 UTC, merged