[GAUSSDB]: New resource `gaussdb_mysql_instance_v3`
opentelekomcloud/terraform-provider-opentelekomcloud pull request #2327
Opened 2023-09-29 17:37 UTC by artem-lifshits

## Summary of the Pull Request
New resource to manage GaussDB MySql

## PR Checklist

* [ ] Refers to: #xxx
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccMysqlGaussdbInstanceV3Basic
--- PASS: TestAccMysqlGaussdbInstanceV3Basic (1052.62s)
PASS

Process finished with the exit code 0
```

2023-09-29 18:14 UTC, Aloento submitted a review, later dismissed

2023-09-29 18:20 UTC, vladimirvshivkov submitted a review, later dismissed

2023-10-02 08:14 UTC, anton-sidelnikov requested changes

2023-10-02 08:14 UTC, anton-sidelnikov commented on docs/resources/gaussdb_mysql_instance_v3.md
> +## Import
did you check import?

2023-10-02 08:14 UTC, anton-sidelnikov commented on opentelekomcloud/services/gaussdb/resource_opentelekomcloud_gaussdb_mysql_instance_v3.go
> +	d.SetId(id)
why not in oneline?

2023-10-02 08:14 UTC, anton-sidelnikov commented on opentelekomcloud/services/gaussdb/resource_opentelekomcloud_gaussdb_mysql_instance_v3.go
> +	}
why? I think this can break the state

2023-10-02 10:53 UTC, Aloento approved these changes, later dismissed

2023-10-02 11:00 UTC, anton-sidelnikov submitted a review, later dismissed

2023-10-02 11:00 UTC, anton-sidelnikov approved these changes

2023-10-02 11:25 UTC, merged