[Feat.] DMS: Add new resource opentelekomcloud_dms_topic_v2
opentelekomcloud/terraform-provider-opentelekomcloud pull request #2766
Opened 2024-12-13 13:14 UTC by artem-lifshits

## Summary of the Pull Request
New resource `opentelekomcloud_dms_topic_v2` introduced.
`opentelekomcloud_dms_topic_v1` is deprecated due to api goingout-of-date. 

## PR Checklist

* [x] Refers to: #2741
* [x] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.
* [x] Release notes added.

## Acceptance Steps Performed

```
=== RUN   TestAccDmsTopicsV2_basic
--- PASS: TestAccDmsTopicsV2_basic (647.36s)
PASS

Process finished with the exit code 0

=== RUN   TestAccDmsTopicsV1_basic
--- PASS: TestAccDmsTopicsV1_basic (649.04s)
PASS

Process finished with the exit code 0

```

2024-12-13 13:18 UTC, muneeb-jan approved these changes, later dismissed

2024-12-13 14:16 UTC, anton-sidelnikov requested changes

2024-12-13 14:16 UTC, anton-sidelnikov commented on docs/resources/dms_topic_v2.md
> +* `instance_id` - (Required) Indicates the ID of primary DMS instance.
please add type and forcenew details

2024-12-13 14:16 UTC, anton-sidelnikov commented on docs/resources/dms_topic_v2.md
> +* `max_partitions` - Total partitions number.
import?

2024-12-13 14:16 UTC, anton-sidelnikov commented on opentelekomcloud/acceptance/dms/resource_opentelekomcloud_dms_topic_v2_test.go
> +		CheckDestroy:      testAccCheckDmsV1InstanceDestroy,
please use InitResourceCheck

2024-12-13 14:16 UTC, anton-sidelnikov commented on opentelekomcloud/services/dms/common.go
> +	dmsV1Deprecated     = "This resource API is deprecated. Please use opentelekomcloud_dms_topic_v2 instead."
also add message in doc

2024-12-16 09:40 UTC, anton-sidelnikov approved these changes

2024-12-16 10:03 UTC, merged