Fix rds subnet_id/network_id confusion
opentelekomcloud/terraform-provider-opentelekomcloud pull request #382
Opened 2019-10-04 08:42 UTC by r0b2g1t

During my test I noticed, that when creating an RDS resource not the `subnet_id` is needed, but the `network_id` is required.

The fix replaces the variable `subnet_id` with `network_id`, both in the code and in the documentation.

2019-10-04 12:23 UTC, tstrohmeier commented
The naming in the RDS API is `subnet_id` as mentioned here: https://github.com/terraform-providers/terraform-provider-opentelekomcloud/pull/267#discussion_r278509705
API Doc: https://docs.otc.t-systems.com/en-us/api/rds/en-us_topic_0160329112.html

In the OTC UI the `subnet.id` is displayed as `Network ID` and the `neutron_subnet_id` as `Subnet ID`. I think it would be better to talk with TSY/Huwai and clarify which ID is the "subnet id". Until then it would be better to keep this PR open since this change would break existing implementations.

2019-10-04 12:43 UTC, r0b2g1t commented
> The naming in the RDS API is `subnet_id` as mentioned here: [#267 (comment)](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/pull/267#discussion_r278509705)
> API Doc: https://docs.otc.t-systems.com/en-us/api/rds/en-us_topic_0160329112.html
> 
> In the OTC UI the `subnet.id` is displayed as `Network ID` and the `neutron_subnet_id` as `Subnet ID`. I think it would be better to talk with TSY/Huwai and clarify which ID is the "subnet id". Until then it would be better to keep this PR open since this change would break existing implementations.

Thanks for your response. I will contact T-Systems/Huawei to discuss this topic. :-)

@gtema Is this possibly a topic where you can support?

2019-10-04 12:50 UTC, tstrohmeier commented
@r0b2g1t Perfect! Can you include me in the discussion please?

2019-10-04 12:53 UTC, r0b2g1t commented
@tstrohmeier I do.

2019-10-04 12:54 UTC, tstrohmeier commented
@r0b2g1t Thanks!

2019-10-04 13:39 UTC, gtema commented
@r0b2g1t, Yes, I know it's a mess - the same in otcextensions. I will try to clarify and enforce doc update

2019-10-04 15:48 UTC, r0b2g1t commented
> @r0b2g1t, Yes, I know it's a mess - the same in otcextensions. I will try to clarify and enforce doc update

Thanks a lot, do you need an request email or ticket for this topic?

2019-10-04 15:50 UTC, gtema commented
nope

2019-10-14 11:04 UTC, tstrohmeier commented
@gtema Do you have any update on this?

2019-10-17 10:25 UTC, gtema commented
well, good and bad news:

- I can confirm, that the subnet_id is expecting an ID of neutron network. It comes from the Huawei mix of FusionSphere networks and subnets. FS subnet is a neutron net. There are multiple other services (incl. CCE), which expected neutron_network_id, but the parameter is called subnet_id. It is actually likely the case in all of the FS specific services. That is also the reason, why in the UI you see neutron network_id as a subnet_id
- You can understand, nobody will do such a big change as a parameter renaming in the production system. The only chance would be to have this fixed in the next revision (API version) - and unfortunately likely this means - never.

I will try to go for escalations, but I can't promise anything.

For the moment (or better to say with respect to this particular issue) I would suggest the same, what we do in otcextensions for the CLI type - rename parameter. So end-user is passing neutron network_id, which is then passed as a subnet_id parameter into the API.

2019-10-18 10:30 UTC, gtema commented on opentelekomcloud/resource_opentelekomcloud_rds_instance_v3.go
> +		params["network_id"] = v
I guess here it should stay subnet_id, since the API really expects subnet_id parameter, but with neutron network id content

2019-10-18 11:10 UTC, tstrohmeier commented
@gtema Thank you for clarification.and the deep insights.

I just want to point out that we use the current TF RDS v3 resource in production for several systems.

2019-10-22 11:34 UTC, niuzhenguo commented
Please follow the instruction of provider attribute renaming https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-attribute-rename

2019-10-25 12:54 UTC, tstrohmeier commented
Thank you @niuzhenguo . This s what would be needed here.

2019-11-20 23:48 UTC, tstrohmeier requested changes

2019-11-20 23:48 UTC, tstrohmeier commented on website/docs/r/rds_instance_v3.html.markdown
> +* `network_id` -
As pointed out by @niuzhenguo there should be a smooth migration.
https://www.terraform.io/docs/extend/best-practices/deprecations.html#renaming-a-required-attribute

* `subnet_id` 
**Deprecated**
(Optional)
Specifies the subnet id. Changing this parameter will create a new resource. Either subnet id or network id MUST be specified.
* `network_id ` 
(Optional)
Specifies the network id. Changing this parameter will create a new resource. Either subnet id or network id MUST be specified.

2019-12-07 18:51 UTC, tstrohmeier commented on website/docs/r/rds_instance_v3.html.markdown
> +* `network_id` -
@r0b2g1t Why is this conversation marked as resolved?

2020-02-11 22:13 UTC, tstrohmeier commented
@r0b2g1t As pointed out by niuzhenguo there should be a smooth migration.
https://www.terraform.io/docs/extend/best-practices/deprecations.html#renaming-a-required-attribute

* `subnet_id` 
**Deprecated**
(Optional)
Specifies the subnet id. Changing this parameter will create a new resource. Either subnet id or network id MUST be specified.
* `network_id ` 
(Optional)
Specifies the network id. Changing this parameter will create a new resource. Either subnet id or network id MUST be specified.

2020-09-09 13:15 UTC, outcatcher commented
Hi @r0b2g1t, this PR is stale for 7 months already. Do you still need it?

2020-09-11 13:48 UTC, closed without merging