Add project_name to CTS
opentelekomcloud/terraform-provider-opentelekomcloud pull request #538
Opened 2020-07-08 10:40 UTC by lego963

Closes: #530

2020-07-08 12:33 UTC, outcatcher requested changes

2020-07-08 12:33 UTC, outcatcher commented on opentelekomcloud/util.go
> +func GetProjectName(d *schema.ResourceData, config *Config) string {
Project name from the schema is never used

2020-07-08 12:33 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cts_tracker_v1.go
> +	d.Set("project_name", GetProjectName(d, config))
Project name in schema is always overwritten by current project

2020-07-10 11:37 UTC, lego963 commented
Need to add same possibility to smn_topic_v2

2020-07-27 17:00 UTC, lego963 commented
Close due to remove base repository

2020-07-27 17:00 UTC, closed without merging