Add project_name field to SMN topic
opentelekomcloud/terraform-provider-opentelekomcloud pull request #544
Opened 2020-07-10 12:24 UTC by lego963

This pr is part of #538

2020-07-10 16:15 UTC, outcatcher requested changes

2020-07-10 16:15 UTC, outcatcher commented on opentelekomcloud/util.go
> +		value := projectNameField.(string)
Please move `.(string)` to before `if`

2020-07-10 16:15 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_smn_topic_v2_test.go
> +func TestAccSMNV2Topic_schemaProjectName(t *testing.T) {
You're not trying to create SMN topic for another project. Please add second project name for that.

2020-07-27 11:51 UTC, lego963 commented
Close due to remove base repository

2020-07-27 11:51 UTC, closed without merging