Docs migrations
opentelekomcloud/terraform-provider-opentelekomcloud pull request #593
Opened 2020-08-27 12:07 UTC by lego963

Resolve: #577

2020-08-27 12:17 UTC, gtema requested changes
Please go through the readme and fix links to old repo location (unfortunately GH does not allow commenting lines not touched by PR)

2020-08-27 15:44 UTC, gtema commented
you should not remove the "--- frontmatter ---" headers from files. At least page_title should stay (actually perhaps start using subcategory). Read carefully https://www.terraform.io/docs/registry/providers/docs.html

2020-08-27 16:32 UTC, lego963 commented
Yes, I will return it, now I format the documents and fix them with strange or insufficient info

2020-08-31 09:25 UTC, gtema approved these changes, later dismissed
Whew.
I don't know whether we will get problems with removal of `title`, but we can re-add it then.

2020-08-31 09:26 UTC, outcatcher requested changes

2020-08-31 09:26 UTC, outcatcher commented on docs/data-sources/antiddos_v1.md
> +subcategory: "AntiDDos"
It should be `DDoS`, not `DDos`

2020-08-31 09:44 UTC, lego963 commented
>`page_title - The title of this document, which will display in the docs navigation. This is only required for documents in the guides/ folder.`
according to https://www.terraform.io/docs/registry/providers/docs.html

2020-08-31 10:01 UTC, gtema commented
> > `page_title - The title of this document, which will display in the docs navigation. This is only required for documents in the guides/ folder.`
> 
> according to https://www.terraform.io/docs/registry/providers/docs.html

it's not about "requires", it's about how the page name would be shown by the render tool, but even before it was not very much useful

2020-08-31 10:02 UTC, gtema commented
hmm, the build is also failing in a weird way

2020-08-31 12:49 UTC, outcatcher approved these changes, later dismissed

2020-08-31 13:56 UTC, gtema approved these changes
No clue how to review 271 files other that simply by diagonal

2020-08-31 14:06 UTC, merged