add k8sTags to cce node resource
opentelekomcloud/terraform-provider-opentelekomcloud pull request #621
Opened 2020-09-21 14:24 UTC by cgroschupp

Allow to add k8s tags.

https://github.com/huaweicloud/golangsdk/blob/master/openstack/cce/v3/nodes/results.go#L75

2020-09-21 18:14 UTC, outcatcher requested changes
Thanks for your contribution to the OTC Terraform provider! 

The only remark ― can you please also implement validation for `k8sTags` as described in documentation:
```
Key: Enter 1 to 63 characters starting with a letter or digit. Only letters, digits, hyphens (-), underscores (_), and periods (.) are allowed. A DNS subdomain can be prefixed to a key and contain a maximum of 253 characters. Example DNS subdomain: example.com/my-key
Value: The value can be left blank or a string of 1 to 63 characters starting with a letter or digit. Only letters, digits, hyphens (-), underscores (_), and periods (.) are allowed in the character string.
```

2020-09-22 12:18 UTC, outcatcher requested changes
Sorry for the slow response ― there are issues with CCE tests

2020-09-22 12:18 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +		if !regexp.MustCompile(pattern).MatchString(key) {
There are duplicating operations for each iteration.
Please make `pattern` a const and move `regexp.MustCompile(pattern)` out of the `for` cycle

2020-09-24 09:47 UTC, outcatcher commented
@cgroschupp would you like to continue with the PR? You need to resolve conflict with `master` branch now.

2020-09-25 08:57 UTC, outcatcher commented
@cgroschupp There are conflicts with the base branch. Can you please merge `master` into your branch first (or rebase your branch onto up-to-date master)?

2020-09-25 09:02 UTC, cgroschupp commented
@outcatcher sorry for the delay

2020-09-25 09:17 UTC, lego963 approved these changes

2020-09-25 10:01 UTC, outcatcher approved these changes
Tests passed

2020-09-25 10:08 UTC, merged