Update r/csbs_backup_policy_v1 with new field
opentelekomcloud/terraform-provider-opentelekomcloud pull request #628
Opened 2020-09-25 10:22 UTC by lego963

2020-09-25 15:50 UTC, outcatcher requested changes

2020-09-25 15:50 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_csbs_backup_policy_v1.go
> +	me := &multierror.Error{}
You can skip `me` initialization, just `me := multierror.Append(nil, ...` instead

2020-09-25 15:50 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_csbs_backup_policy_v1.go
> +		return fmt.Errorf("[DEBUG] Error saving resource to state for OpenTelekomCloud CSBS backup policy (%s): %s", d.Id(), err)
Too much overlapping between error messages, you can move the pattern to const section and pass the used field to that pattern

2020-09-28 10:16 UTC, outcatcher approved these changes

2020-09-28 10:22 UTC, lego963 commented
=== RUN   TestAccCSBSBackupPolicyV1_basic
--- PASS: TestAccCSBSBackupPolicyV1_basic (198.71s)
=== RUN   TestAccCSBSBackupPolicyV1_timeout
--- PASS: TestAccCSBSBackupPolicyV1_timeout (128.67s)
PASS

Process finished with exit code 0

2020-09-28 10:29 UTC, merged