Update outdated github templates
opentelekomcloud/terraform-provider-opentelekomcloud pull request #629
Opened 2020-09-28 11:06 UTC by lego963

2020-09-28 16:12 UTC, outcatcher requested changes

2020-09-28 16:12 UTC, outcatcher commented on .github/labeler.yml
> +  - opentelekomcloud/*
Would bugfixes get the same `enhancement` label?

2020-09-29 07:57 UTC, outcatcher approved these changes

2020-09-29 07:58 UTC, lego963 commented
recheck

2020-09-29 08:20 UTC, gtema commented
regate

2020-09-29 08:27 UTC, merged