Change huaweisdk to gophertelekomcloudSdk
opentelekomcloud/terraform-provider-opentelekomcloud pull request #641
Opened 2020-10-06 15:03 UTC by lego963

## Summary of the Pull Request

Change huaweicloudSDdk to gophertelekomcloudSdk 

## Acceptance Steps Performed

No one tf module wasn't tested for 06.10.2020

2020-10-06 15:28 UTC, outcatcher requested changes
Please run as many tests as possible

2020-10-14 11:41 UTC, lego963 commented
recheck

2020-10-14 14:30 UTC, outcatcher commented on opentelekomcloud/config.go
> +	gophersdk "github.com/opentelekomcloud/gophertelekomcloud/openstack"
Why not use `openstack` without rename?

2020-10-15 08:39 UTC, outcatcher approved these changes, later dismissed

2020-10-15 08:45 UTC, lego963 commented
recheck

2020-10-15 08:48 UTC, lego963 commented
recheck

2020-10-15 09:22 UTC, lego963 commented
recheck

2020-10-15 11:37 UTC, outcatcher approved these changes

2020-10-15 11:44 UTC, merged