RDSv3: Migrate to gopher sdk
opentelekomcloud/terraform-provider-opentelekomcloud pull request #660
Opened 2020-10-21 13:04 UTC by lego963

## Summary of the Pull Request

## PR Checklist

* [ ] Refers to: #xxx
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

2020-10-22 09:09 UTC, lego963 commented
Delete method requires changes in SDK

2020-10-28 07:50 UTC, outcatcher commented
recheck

2020-10-28 18:47 UTC, outcatcher approved these changes

2020-10-28 18:47 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_rds_instance_v3.go
> +			"switch_strategy": {
Maybe move this to another PR?

2020-10-28 18:47 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_rds_instance_v3.go
> +			"updated": {
Same as  previous

2020-10-28 18:47 UTC, outcatcher requested changes
Approved by mistake, see previous comments

2020-10-30 07:04 UTC, anton-sidelnikov approved these changes

2020-10-30 07:26 UTC, outcatcher approved these changes

2020-10-30 07:34 UTC, merged