suppress schema diff in CCE version
opentelekomcloud/terraform-provider-opentelekomcloud pull request #666
Opened 2020-10-26 08:12 UTC by anton-sidelnikov

## Summary of the Pull Request

## PR Checklist

* [ ] Refers to: #664
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

2020-10-26 08:18 UTC, outcatcher requested changes

2020-10-26 08:18 UTC, outcatcher commented on opentelekomcloud/diff_suppress_funcs.go
> +	if strings.ToLower(old) == strings.ToLower(new) {
The problem in #664 was difference between `v1.15.11-r1` and `v1.15.11`, not a case difference

2020-10-26 08:18 UTC, outcatcher commented on opentelekomcloud/diff_suppress_funcs.go
> +func suppressSchemaDiff(k, old, new string, d *schema.ResourceData) bool {
The name should describe how this actually is used

2020-10-26 17:37 UTC, lego963 approved these changes, later dismissed

2020-10-27 17:54 UTC, outcatcher commented on opentelekomcloud/diff_suppress_funcs.go
> +		if oldArray[i] != newArray[i] {
If we make a `break` here, will the result be the same?

2020-10-28 08:00 UTC, lego963 approved these changes

2020-10-28 08:15 UTC, outcatcher approved these changes

2020-10-28 08:24 UTC, merged