Add possibility to unassign eip
opentelekomcloud/terraform-provider-opentelekomcloud pull request #696
Opened 2020-11-06 17:32 UTC by lego963

## Summary of the Pull Request
This pr contains workaround of eip issue with cce_node_v3. It can only diassociate eip.

## PR Checklist

* [ ] Refers to: #678 
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```

Process finished with exit code 0
```

2020-11-09 07:16 UTC, outcatcher requested changes

2020-11-09 07:16 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +	// release ip if assigned
And if other EIP params has changed?

2020-11-09 07:16 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +		if newBandWidth == 0 {
And if bandwidth changed, e.g. from 10 to 100?

2020-11-09 13:38 UTC, outcatcher requested changes

2020-11-09 13:38 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +		} else if newBandWidth > 0 && floatingIp == nil {
What is the goal for ` && floatingIp == nil` check?

2020-11-09 13:38 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +			if err := resourceCCENodeV3DeleteAssociateIP(d, config, serverId, floatingIp); err != nil {
You can check the error after the end of the `if... else if ..` block

2020-11-09 13:38 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3_test.go
> +					testAccCheckCCENodeV3Exists("opentelekomcloud_cce_node_v3.node_1", "opentelekomcloud_cce_cluster_v3.cluster_1", &node),
Please add check for bandwidth size

2020-11-09 15:29 UTC, anton-sidelnikov approved these changes, later dismissed

2020-11-09 15:45 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +				ChargeMode: "traffic",
Only `ShareType` is a required field. Why do you hardcode optional parameters?

2020-11-09 15:45 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +				ChargeMode: "traffic",
Also, where possible, you should take values from the schema

2020-11-11 07:55 UTC, anton-sidelnikov approved these changes, later dismissed

2020-11-11 09:00 UTC, outcatcher approved these changes, later dismissed

2020-11-11 09:37 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3_test.go
> +			},
Can you please add a step with assigning EIPs back

2020-11-11 09:56 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +
You can find removed/added `eip_ids` with `schema.Set.Difference`

2020-11-11 12:17 UTC, anton-sidelnikov approved these changes, later dismissed

2020-11-12 10:28 UTC, outcatcher commented
Postponed to v1.22 due to CCE  testing problems

2020-11-17 11:43 UTC, outcatcher approved these changes

2020-11-17 13:33 UTC, merged