Add missing fields to cce_cluster_v3
opentelekomcloud/terraform-provider-opentelekomcloud pull request #699
Opened 2020-11-09 16:27 UTC by outcatcher

# Summary of the Pull Request
Add `kubernetes_svc_ip_range` and `kube_proxy_mode` fields to `cce_cluster_v3` resource
Update `opentelekomcloud/gophertelekomcloud` dependency

## PR Checklist

* [x] Refers to: #680 
* [x] Tests added/passed.
* [ ] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

2020-11-09 16:34 UTC, lego963 commented on opentelekomcloud/resource_opentelekomcloud_cce_cluster_v3.go
> +	d.SetId(n.Metadata.Id)
it's already set before read in 280 line

2020-11-09 16:36 UTC, lego963 requested changes
comments

2020-11-10 10:53 UTC, lego963 commented on docs/resources/cce_cluster_v3.md
> +* `kube_proxy_mode` - (Optional) Service forwarding mode. Two modes are available:
please add new ref there ```Attributes Reference``` too

2020-11-10 11:11 UTC, outcatcher commented on docs/resources/cce_cluster_v3.md
> +* `kube_proxy_mode` - (Optional) Service forwarding mode. Two modes are available:
There is a note there: 
>All above argument parameters can be exported as attribute parameters along with attribute reference.

2020-11-10 11:23 UTC, lego963 submitted a review, later dismissed

2020-11-10 14:44 UTC, lego963 approved these changes

2020-11-10 15:21 UTC, anton-sidelnikov commented on opentelekomcloud/resource_opentelekomcloud_cce_cluster_v3.go
> +		d.Set("name", n.Metadata.Name),
where is ID?

2020-11-10 15:22 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_cluster_v3.go
> +		d.Set("name", n.Metadata.Name),
It's set in the create

2020-11-10 15:25 UTC, anton-sidelnikov approved these changes

2020-11-10 15:38 UTC, merged