Add CCE addon support
opentelekomcloud/terraform-provider-opentelekomcloud pull request #711
Opened 2020-11-13 15:02 UTC by outcatcher

## Summary of the Pull Request
Implement CCE addon installation using new resource `resource_opentelekomcloud_cce_addon_v3`
Implement #536

## PR Checklist

* [x] Refers to: #536
* [ ] Tests added/passed.
* [ ] Documentation updated.

## Acceptance Steps Performed
**TBD**

SDK changes required for add-on update

2020-11-13 15:55 UTC, outcatcher commented
recheck

2020-11-17 10:08 UTC, outcatcher commented
recheck

2020-12-15 13:55 UTC, outcatcher commented
OTC issue fixed: 
https://jira.tsi-dev.otc-service.com/browse/OCS-2690

2020-12-15 16:27 UTC, outcatcher commented
recheck

2020-12-15 18:39 UTC, lego963 requested changes

2020-12-15 18:39 UTC, lego963 commented on docs/resources/cce_addon_v3.md
> +  name                    = "%s"
strange name, change pls

2020-12-15 18:39 UTC, lego963 commented on docs/resources/cce_addon_v3.md
> +      swr_user        = "hwofficial"
can we change user name to something else?

2020-12-15 18:39 UTC, lego963 commented on opentelekomcloud/resource_opentelekomcloud_cce_addon_v3.go
> +				Computed: true,
I suppose that we need to validate this argument both with `template_name`
If it's possible

2020-12-15 18:39 UTC, lego963 commented on opentelekomcloud/resource_opentelekomcloud_cce_node_v3.go
> +			Os:          "EulerOS 2.5",
why did you change this file?

2020-12-16 07:43 UTC, lego963 approved these changes

2020-12-16 08:03 UTC, merged