Implement DDS flavors data source
opentelekomcloud/terraform-provider-opentelekomcloud pull request #718
Opened 2020-11-23 15:43 UTC by lego963

## Summary of the Pull Request

## PR Checklist

* [ ] Refers to: #xxx
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
=== RUN   TestAccDDSFlavorV3DataSource_basic
--- PASS: TestAccDDSFlavorV3DataSource_basic (38.33s)
PASS

Process finished with exit code 0
```

2020-11-23 18:42 UTC, outcatcher requested changes

2020-11-23 18:42 UTC, outcatcher commented on opentelekomcloud/data_source_opentelekomcloud_dds_flavors_v3.go
> +	d.SetId("flavors")
Is ID is always the same? Won't there be a problem if several data source instances are used?

2020-11-23 18:42 UTC, outcatcher commented on opentelekomcloud/data_source_opentelekomcloud_dds_flavors_v3.go
> +func filterFlavor(item flavors.Flavor, flavorType, vCpus, memory string) bool {
Better to rename it to something like `matchesFilters`

2020-11-23 18:42 UTC, outcatcher commented on opentelekomcloud/data_source_opentelekomcloud_dds_flavors_v3.go
> +	flavorList := make([]map[string]interface{}, 0)
`flavorList` and `flavorsList` are too similar, please rename variables to make it easier to distinguish between them

2020-11-23 18:42 UTC, outcatcher commented on opentelekomcloud/data_source_opentelekomcloud_dds_flavors_v3.go
> +	filterType := d.Get("type").(string)
Maybe name it something like `expectedType`, `expectedVCPUs`, etc.?

2020-11-23 18:42 UTC, outcatcher commented on opentelekomcloud/data_source_opentelekomcloud_dds_flavors_v3_test.go
> +		if rs.Primary.ID == "" {
This is a trivial case, as ID is always set to `flavors`

2020-11-24 07:57 UTC, outcatcher approved these changes

2020-11-24 07:57 UTC, anton-sidelnikov approved these changes

2020-11-24 08:13 UTC, merged