Add paramerter_template support
opentelekomcloud/terraform-provider-opentelekomcloud pull request #784
Opened 2021-01-15 09:56 UTC by lego963

## Summary of the Pull Request

Add possibility to set `configuration_template_id`
Deprecate `param_group_id`

## PR Checklist

* [ ] Refers to: #445
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
=== RUN   TestAccSomethingV0_basic
--- PASS: TestAccSomethingV0_basic (101.71s)
=== RUN   TestAccSomethingV0_timeout
--- PASS: TestAccSomethingV0_timeout (128.67s)
PASS

Process finished with exit code 0
```

2021-01-15 10:04 UTC, outcatcher commented
recheck

2021-01-15 10:10 UTC, outcatcher requested changes

2021-01-15 10:10 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_rds_instance_v3.go
> +				Deprecated: "Please use `configuration_template_id` instead",
Please add `ConflictsWith`

2021-01-15 10:10 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_rds_instance_v3.go
> +			"configuration_template_id": {
It's possible to update it using configuration template apply

2021-01-18 09:31 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_rds_configuration_v3.go
> +	d.SetId(n.ID)
ID should not be set in `read`

2021-01-18 09:34 UTC, outcatcher requested changes

2021-01-18 09:34 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_rds_configuration_v3.go
> +	d.SetId(n.ID)
ID should not be set in `read`

2021-01-18 09:34 UTC, outcatcher commented on go.sum
> +github.com/opentelekomcloud/gophertelekomcloud v0.2.1-0.20210115210116-fd530cf59a68 h1:wE3DaTowb7ktF0zWxfzfl0mGjFHAJ+/wRgNeqPNWlN8=
Please run `go mod tidy`

2021-01-18 09:34 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_rds_instance_v3.go
> +		_, newParamGroupRaw := d.GetChange("param_group_id")
You can simply use `d.Get` for getting updated value

2021-01-18 10:44 UTC, anton-sidelnikov approved these changes

2021-01-18 10:45 UTC, outcatcher approved these changes

2021-01-18 10:55 UTC, merged