[CCE] Resource opentelekomcloud_cce_node_pool_v3
opentelekomcloud/terraform-provider-opentelekomcloud pull request #807
Opened 2021-01-22 10:47 UTC by philippeckel

## Summary of the Pull Request
This is adding resource node pool for CCE.

`make test` failing with:

```golang
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
        xargs -t -n4 go test  -timeout=30s -parallel=4
go test '-timeout=30s' '-parallel=4' github.com/opentelekomcloud/terraform-provider-opentelekomcloud github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud 
?       github.com/opentelekomcloud/terraform-provider-opentelekomcloud [no test files]
# github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud [github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud.test]
opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3_test.go:140:29: cannot use rName (type string) as type *testing.T in argument to TestAccCCEClusterV3_basic
opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3_test.go:140:29: TestAccCCEClusterV3_basic(rName) used as value
FAIL    github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud [build failed]
FAIL
make: *** [GNUmakefile:13: test] Error 123
```

## PR Checklist

* [X] Refers to: #806 
* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

## Acceptance Steps Performed

```
=== RUN   TestAccSomethingV0_basic
--- PASS: TestAccSomethingV0_basic (101.71s)
=== RUN   TestAccSomethingV0_timeout
--- PASS: TestAccSomethingV0_timeout (128.67s)
PASS

Process finished with exit code 0
```

2021-01-22 11:24 UTC, outcatcher requested changes

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +			"region": {
`region` is never used

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +			"pool_type": {
`pool_type` is never used

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +			"data_volumes": {
`data_volumes` is a required field, but it is only set and never read

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +			"taints": {
`taints` is never used

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +func ResourceCCENodePool() *schema.Resource {
The standard name for the resource function would be `resourceCCENodePoolV3`

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +		Timeout:    d.Timeout(schema.TimeoutCreate),
`Update` timeout should be used in this case ― you need to add `Update` to `Timeouts` and use `schema.TimeoutUpdate` here

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +func recursiveNodePoolCreate(cceClient *golangsdk.ServiceClient, opts nodepools.CreateOptsBuilder, ClusterID string, errCode int) (*nodepools.NodePool, string) {
You can drop `errCode` argument (as its value is always the same) and use `error` instead of `string` in return values.

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +				return recursiveNodePoolCreate(cceClient, opts, ClusterID, 403)
Recursion doesn't have an end condition.

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3_test.go
> +`, TestAccCCEClusterV3_basic(rName), rName, rName)
`TestAccCCEClusterV3_basic` is a test method. What are you trying to pass to the format expression?

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +	d.Set("priority", s.Spec.Autoscaling.Priority)
It's safer to catch all errors produced by `d.Set` with `multierror`. E.g.:
```go
	me := multierror.Append(
		d.Set("name", s.Metadata.Name),
		...
	)

	if err := me.ErrorOrNil(); err != nil {
		return fmt.Errorf("error setting CCE Node Pool attributes: %s", err)
	}
```

2021-01-22 11:24 UTC, outcatcher commented on opentelekomcloud/resource_opentelekomcloud_cce_node_pool_v3.go
> +		return fmt.Errorf("Error creating Ope Telekom Cloud CCE Node Pool client: %s", err)
Here and further.
It's considered a better code style to not start error string with a capital letter:
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

2021-01-22 11:28 UTC, outcatcher commented
Additionally: please add documentation, if possible. And add `opentelekomcloud_cce_node_pool_v3` to `ResourcesMap` in `provider.go`.

2021-01-22 12:08 UTC, philippeckel commented
@outcatcher this was basically an adoption of https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/huaweicloud/resource_huaweicloud_cce_node_pool.go  ... will look into your comments, thanks!

2021-02-01 16:09 UTC, outcatcher commented
@philippeckel Are you planning on finishing this PR yourself? If no, we do it :slightly_smiling_face:

2021-02-02 22:04 UTC, philippeckel commented
@outcatcher 

a) you're the better Go developer for sure :-)
b) I cannot dedicate enough time

so yes please and thanks a lot!

This would not only help us to get node pools via Terraform but also to install the OTC Autoscaler plugin which needs customer managed node pools.

Thanks :-)

2021-02-05 11:18 UTC, outcatcher commented
Followed-up by @anton-sidelnikov in #825

2021-02-05 11:18 UTC, closed without merging