Add CBR vault v3 resource
opentelekomcloud/terraform-provider-opentelekomcloud pull request #833
Opened 2021-02-08 16:10 UTC by outcatcher

## Summary of the Pull Request
Implement CBR vault v3 resource

## PR Checklist

* [x] Refers to: #724
* [x] Tests added/passed.
* [ ] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
=== RUN   TestAccCBRVaultV3_basic
--- PASS: TestAccCBRVaultV3_basic (45.92s)
PASS

Process finished with exit code 0
```

2021-02-09 15:24 UTC, anton-sidelnikov requested changes

2021-02-09 15:24 UTC, anton-sidelnikov commented on opentelekomcloud/resource_opentelekomcloud_cbr_vault_v3.go
> +		billingRead(d, &vault.Billing),
mb billingSet?

2021-02-09 20:24 UTC, anton-sidelnikov approved these changes

2021-02-10 06:55 UTC, outcatcher commented
recheck

2021-02-10 07:34 UTC, lego963 approved these changes

2021-02-10 07:39 UTC, anton-sidelnikov approved these changes

2021-02-10 07:57 UTC, merged