Add `enable_authority` and `admin_pass` support
opentelekomcloud/terraform-provider-opentelekomcloud pull request #902
Opened 2021-03-11 20:36 UTC by outcatcher

## Summary of the Pull Request
Add `enable_authority` and `admin_pass` support for CSS cluster v1

Move to SDK implementation of CSS cluster v1

Resolve #880, #889

## PR Checklist

* [x] Refers to: #889, #880 
* [ ] Tests added/passed.
* [x] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
To be executed...
```

2021-03-12 07:09 UTC, outcatcher commented
recheck

2021-03-12 08:10 UTC, lego963 approved these changes, later dismissed

2021-03-12 08:41 UTC, anton-sidelnikov requested changes

2021-03-12 08:41 UTC, anton-sidelnikov commented on opentelekomcloud/services/css/resource_opentelekomcloud_css_cluster_v1.go
> +		return fmt.Errorf("errro reading cluster value: %s", err)
errro

2021-03-12 12:54 UTC, anton-sidelnikov submitted a review, later dismissed

2021-03-12 15:57 UTC, lego963 approved these changes, later dismissed

2021-03-12 16:26 UTC, outcatcher commented
Unstable acceptance

2021-03-15 15:25 UTC, lego963 approved these changes

2021-03-15 16:07 UTC, anton-sidelnikov approved these changes

2021-03-15 16:18 UTC, merged