[ECS] Update `compute_instance_v2` doc
opentelekomcloud/terraform-provider-opentelekomcloud pull request #929
Opened 2021-03-23 09:46 UTC by lego963

## Summary of the Pull Request
Update description of `security_groups` in `resource/opentelekomcloud_compute_instance_v2`
Resolves: #912

## PR Checklist

* [ ] Refers to: #912
* [ ] Documentation updated.

2021-03-23 10:10 UTC, outcatcher requested changes

2021-03-23 10:10 UTC, outcatcher commented on docs/resources/compute_instance_v2.md
> +  or IDs (recommended) to associate with the server. Changing this results in adding/removing
We should not recommend an approach leading to always updating not changed resource :slightly_frowning_face:

2021-03-24 06:48 UTC, outcatcher commented on docs/resources/compute_instance_v2.md
> +~> **Warning:** Names should be used and not IDs. Security group names should be **unique**
Should be a `**Warning**` without a colon. Automatically generated `Note` has no colon.

Also, there should be a comma before `otherwise`

2021-03-24 07:31 UTC, outcatcher approved these changes

2021-03-24 08:06 UTC, anton-sidelnikov approved these changes

2021-03-24 08:22 UTC, merged